/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    LoginWithDiscord: typeof import('./components/LoginWithDiscord.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpellComparison: typeof import('./components/SpellComparison.vue')['default']
    SpellTable: typeof import('./components/SpellTable.vue')['default']
  }
}
